M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu23.10.1} date 2024-10-02T13:11:45+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-02T13:11:45+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu23.10.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.02Y-2.3
X5.89Y-3.79
X6.75Y-2.3
M30
